name: rag_stack

services:
  db_pgvector:
    image: pgvector/pgvector:pg18
    container_name: rag_pgvector
    restart: unless-stopped
    # Load .env files
    env_file: 
     - .env
    environment:
      # Set default value if not in .env
      POSTGRES_USER: ${POSTGRES_USER:-takos}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
    ports:
      # - "5432:5432"
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../data/pgvector_volume:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
    - rag_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rag_pgadmin
    restart: unless-stopped
    depends_on:
      db_pgvector:
        condition: service_healthy
    env_file: 
    - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-takos@local.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-change_me}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"

    volumes:
      - ../data/pgadmin_volume:/var/lib/pgadmin
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
